# Generated by Django 2.1.5 on 2019-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190226_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.TextField(default='Incomplete'),
        ),
    ]
