# Generated by Django 2.1.5 on 2019-03-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190306_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.TextField(default='Incomplete'),
        ),
    ]
